# NumPy Example 1: Store

A store sells 9 different products. Below we have arrays that record
- the number of units sold per product
- the price per product
- the procurement cost per product
- the stock per product at the end of the day

In [1]:
import numpy as np

# 9 products
units_sold = np.array([35, 12, 18, 50,  9, 22, 14, 27, 40])
price      = np.array([20, 15, 12,  8, 30, 18, 25, 10,  6])
cost       = np.array([ 8,  6,  5,  3, 14,  9, 11,  4,  2])
stock      = np.array([10, 40, 11,  8, 25,  6, 30,  9, 15])

## Revenue
Revenue is *units sold* $\times$ *unit price*

We want to compute
- revenue per product
- total revenue

In [2]:
revenue_per_product = units_sold * price
revenue_per_product

array([700, 180, 216, 400, 270, 396, 350, 270, 240])

In [3]:
total_revenue = revenue_per_product.sum()
total_revenue

np.int64(3022)

## Profit
Profit is *units sold* $\times$ (*unit price* $-$ *unit procurement cost*)

We want to compute
- profit per product
- total profit
- the index of the most profitable product

In [4]:
profit_per_product = units_sold * (price - cost)
profit_per_product

array([420, 108, 126, 250, 144, 198, 196, 162, 160])

In [5]:
total_profit = profit_per_product.sum()
total_profit

np.int64(1764)

`np.argmax` returns the index of the maximum element

In [6]:
top_profit_idx = np.argmax(profit_per_product)
top_profit_idx

np.int64(0)

## Restocking
We want to restock all those products that have less than 12 units in stock at the end of the day. We want to order as many units as needed to make the stock hit 20. For other products, we don't want any restocking.

We want to
- compute Boolean mask of products that need restocking
- order quantities for all products
- index of the product that needs most orders
- the amount of products to order for the top product

In [7]:
# mask
need_restock = stock < 12
need_restock

array([ True, False,  True,  True, False,  True, False,  True, False])

`np.where(cond,x,y)` works such that it selects element from `x` if condition is true and `y` otherwise. If `x` and `y` are not specified, it returns the indices of those elements where `cond` is true.

In [8]:
np.where(need_restock)

(array([0, 2, 3, 5, 7]),)

In [9]:
order_qty = np.where(need_restock, 20 - stock, 0)
order_qty

array([10,  0,  9, 12,  0, 14,  0, 11,  0])

In [10]:
most_order_needed_idx = np.argmax(order_qty)
most_order_needed_idx

np.int64(5)

In [11]:
most_order = order_qty[most_order_needed_idx]
most_order

np.int64(14)