# NumPy Example 2: Power

The following matrix represents the electricity consumption of 8 different buildings (rows) across a week (columns Monday to Sunday).

We want to compute averages of electricity consumption and identify inefficient buildings.

In [12]:
import numpy as np

# rows = buildings
# columns = days (Mon Tue Wed Thu Fri Sat Sun)
usage = np.array([
    [28, 30, 29, 31, 32, 30, 29],  # Building 0
    [20, 22, 21, 23, 24, 18, 17],  
    [35, 36, 34, 37, 38, 36, 37],  
    [25, 26, 24, 27, 28, 20, 19],  
    [40, 42, 41, 43, 44, 42, 43],  
    [18, 19, 20, 21, 22, 16, 15],  
    [30, 31, 32, 33, 34, 31, 32],  
    [22, 23, 24, 25, 26, 24, 23],  # Building 7
])

## Average usage
- Compute weekly averages per building

In [13]:
avg_usage = usage.mean(1)
avg_usage

array([29.85714286, 20.71428571, 36.14285714, 24.14285714, 42.14285714,
       18.71428571, 31.85714286, 23.85714286])

## Electricity usage during weekdays and weekends
- Select power usage during weekdays (Mon-Fri)
- Select power usage during weekends (Sat-Sun)
- Compute respective averages per building

In [14]:
usage_weekdays = usage[:,:5]
usage_weekdays

array([[28, 30, 29, 31, 32],
       [20, 22, 21, 23, 24],
       [35, 36, 34, 37, 38],
       [25, 26, 24, 27, 28],
       [40, 42, 41, 43, 44],
       [18, 19, 20, 21, 22],
       [30, 31, 32, 33, 34],
       [22, 23, 24, 25, 26]])

In [15]:
usage_weekends = usage[:,5:]
usage_weekends

array([[30, 29],
       [18, 17],
       [36, 37],
       [20, 19],
       [42, 43],
       [16, 15],
       [31, 32],
       [24, 23]])

In [16]:
avg_usage_weekdays = usage_weekdays.mean(1)
avg_usage_weekdays

array([30., 22., 36., 26., 42., 20., 32., 24.])

In [17]:
avg_usage_weekends = usage_weekends.mean(1)
avg_usage_weekends

array([29.5, 17.5, 36.5, 19.5, 42.5, 15.5, 31.5, 23.5])

## Find inefficient buildings
A building is considered inefficient if
- the daily average is > 30 kWh **and**
- the usage does not go down during weekends

In [18]:
inefficient = (avg_usage > 30) & (avg_usage_weekends >= avg_usage_weekdays)
inefficient

array([False, False,  True, False,  True, False, False, False])

## Weekly usage of inefficient buildings
- List daily usage for inefficient buildings

In [19]:
daily_inefficient = usage[inefficient,:]
daily_inefficient

array([[35, 36, 34, 37, 38, 36, 37],
       [40, 42, 41, 43, 44, 42, 43]])

## Most daily usage
- Which day has the most total usage over all days?
- List the usage for that day for all buildings

In [20]:
daily_total = usage.sum(0)
daily_total

array([218, 229, 225, 240, 248, 217, 215])

In [21]:
max_usage_day = np.argmax(daily_total)
max_usage_day

np.int64(4)

In [22]:
usage_max_day = usage[max_usage_day,:]
usage_max_day

array([40, 42, 41, 43, 44, 42, 43])